site_name:        OpenML.jl
repo_url:         https://github.com/openml/OpenML.jl
site_description: "This is the reference documentation of OpenML.jl"

theme:
    name: "material"
    language: "en"
    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: indigo
          accent: indigo
          scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    font:
        text: "Roboto"
        code: "Roboto Mono"
    icon:
        edit: material/pencil 
        view: material/eye

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true

docs_dir: 'docs/build'

nav:
  - Home: index.md
